import {initLanguageSwitch,isProjectAnchor} from '../project-front/render.mjs?v=cpx-20261009-1436';
const updateLanguageLinks=initLanguageSwitch();
import {renderProject} from './presentation.mjs?v=cpx-20261009-1436';
import {viewFromHash,hashForView} from './routing.mjs';
import {createSession,appendQuestion,appendAssistance,review,retrySession,compareSessions,cloneDraft,publishDraft,validateCase,exportJSON,MODE} from './core.mjs';
import {createStore} from './storage.mjs';
import {adaptCaseBank} from './adapter.mjs';
const $=s=>document.querySelector(s), main=$('#main'), notice=$('#notice');
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const button=(text,action,cls='')=>{const n=el('button',cls,text);n.type='button';n.addEventListener('click',action);return n};
const paragraph=(text,cls='')=>el('p',cls,text);
const clone=x=>structuredClone(x);
let storage;try{storage=localStorage}catch{storage={getItem(){throw Error()},setItem(){throw Error()}}}
const store=createStore(storage);let state=store.load(), view=viewFromHash(window.location?.hash), selected=null, reviewId=null, goalIds=new Set(), draftId=null, selectedIntent=0, dirty=false;
function message(text){notice.textContent=text}
function save(){try{const ok=store.update(state);$('#save-state').textContent=ok?'Saved on this device':'Kept in this tab';if(!ok)message(store.error);return ok}catch(e){message('Could not save records. '+e.message);return false}}
function latestCases(){const map=new Map();for(const c of state.cases){if(!map.has(c.id)||map.get(c.id).version<c.version)map.set(c.id,c)}return [...map.values()]}
function currentCase(){return latestCases().find(c=>c.id===selected)||latestCases()[0]}
function active(){return state.sessions.find(s=>s.id===state.activeSessionId)}
function sessionForCase(){const s=active();return s?.caseId===selected?s:null}
function stamp(c){return `Source ${c.sourceVersion} · Revision ${c.appRevision??c.version}`}
function updateSession(s){state.sessions=state.sessions.map(x=>x.id===s.id?s:x);save()}
function start(c){const s=createSession(c);state.sessions.push(s);state.activeSessionId=s.id;selected=c.id;save();render();$('#question')?.focus()}
function navigate(v,{history=true,resetReview=true}={}){view=viewFromHash(hashForView(v));if(history&&window.location?.hash!==hashForView(view))window.history?.pushState(null,'',hashForView(view));message(store.error||'');if(view==='review'&&resetReview){reviewId=active()?.id||state.sessions.at(-1)?.id;goalIds=new Set()}render();main.focus();window.scrollTo?.(0,0)}
window.addEventListener('hashchange',()=>{if(isProjectAnchor(window.location?.hash)){if(view!=='project')navigate('project',{history:false});return}navigate(viewFromHash(window.location?.hash),{history:false})});
window.addEventListener('popstate',()=>{if(isProjectAnchor(window.location?.hash)){if(view!=='project')navigate('project',{history:false});return}navigate(viewFromHash(window.location?.hash),{history:false})});
let projectCases=[];
function project(){renderProject(main,{example:projectCases[0],counts:{cases:projectCases.length,facts:projectCases.flatMap(c=>c.facts).length,intents:projectCases.flatMap(c=>c.intents).length,expressions:projectCases.flatMap(c=>c.intents.flatMap(i=>i.expressions)).length},navigate,illustration,openExample(id){selected=latestCases().find(c=>c.id===id)?.id||latestCases()[0]?.id;navigate('practice')}})}
document.querySelector('.skip')?.addEventListener('click',e=>{e.preventDefault();main.focus();main.scrollIntoView({block:'start'})});
for(const b of document.querySelectorAll('[data-nav]'))b.onclick=()=>navigate(b.dataset.nav);
function illustration(){const n=el('img');n.src='./assets/listening-illustration.png';n.alt='Two people talking and listening across a desk';return n}
function rail(){const r=el('aside','rail');r.setAttribute('aria-label','Choose a case');r.append(el('h2',null,'Choose a case'),paragraph('Choose a topic to practice.','small'));latestCases().forEach((c,i)=>{const b=button('',()=>{selected=c.id;draftId=null;selectedIntent=0;render()},'case-button'+(selected===c.id?' active':''));b.append(el('span','case-letter',`Case ${String.fromCharCode(65+i)}`),el('span',null,c.title));b.setAttribute('aria-pressed',String(selected===c.id));r.append(b)});return r}
function layout(){const l=el('div','layout'),w=el('section','workspace');l.append(rail(),w);main.append(l);return w}
function speech(role,text){const row=el('div','utterance');row.append(el('span','role',role),paragraph(text,'speech'));return row}
function turnNode(t,index,withHelp=false){const node=el('article','turn');node.id='turn-'+t.id;node.tabIndex=-1;node.append(el('div','small',`Turn ${String(index+1).padStart(2,'0')}`),speech('Student',t.question));if(t.patientResponse!==null){const patient=speech('Patient',t.patientResponse);node.patientText=patient.children[1];node.append(patient)}else node.append(paragraph('No matching response was found. Choose the intended question to connect a response.','system-line'));if(t.assisted||t.matchingMethod==='unmatched')node.append(el('div','turn-meta',t.assisted?'Response linked with intent assistance':'No response · original input retained'));if(withHelp&&t.matchingMethod==='unmatched'){const d=el('details','help');d.append(el('summary',null,'Choose a question intent'));const options=el('div','intent-options');for(const i of sessionForCase().caseSnapshot.intents)options.append(button(i.label,()=>{updateSession(appendAssistance(sessionForCase(),t.id,i.id));render();$('#question')?.focus();const list=$('.transcript');if(list)list.scrollTop=list.scrollHeight}));d.append(paragraph('Links the selected intent to a response and records that assistance was used.','small'),options);node.append(d)}return node}
function practice(){const w=layout(),c=currentCase();if(!c)return;const s=sessionForCase(),snap=s?.caseSnapshot||c;const intro=el('div','intro');intro.append(el('h1',null,'Interview practice'),paragraph('Ask questions, examine the dialogue evidence, and practice again.'),el('h2','case-title',snap.title),el('span','badge','Case practice · authored responses'),el('div','small',stamp(snap)),illustration());w.append(intro);
if(!s){const box=el('div','session-actions');box.append(button('Start a new practice',()=>start(c),'primary'));const prior=state.sessions.filter(x=>x.caseId===c.id).at(-1);if(prior)box.append(button('Continue previous practice',()=>{state.activeSessionId=prior.id;save();render()}));w.append(box,paragraph(c.description,'speech'),paragraph(`${c.profile?.age||''} years old · ${c.profile?.occupation||''}`,'small'));return}
const actions=el('div','session-actions');actions.append(el('span','small',`${s.turns.length} questions recorded`),button('New practice',()=>start(c)));if(s.previousSessionId)actions.append(el('span','small','Retrying with selected goals'));w.append(actions);
const transcript=el('div','transcript');transcript.setAttribute('aria-label','Conversation record');transcript.append(speech('Patient',snap.description));s.turns.forEach((t,i)=>transcript.append(turnNode(t,i,true)));w.append(transcript);
const form=el('form','composer');const label=el('label',null,'Ask the patient');label.htmlFor='question';const row=el('div','composer-row'),q=el('textarea');q.id='question';q.name='question';q.maxLength=4000;q.required=true;q.placeholder='Type your question here.';q.rows=2;const send=el('button','primary','Send');send.type='submit';row.append(q,send,button('Finish practice',()=>{reviewId=s.id;goalIds=new Set();navigate('review',{resetReview:false})}));form.append(label,row);form.onsubmit=e=>{e.preventDefault();if(!q.value.trim())return;try{updateSession(appendQuestion(sessionForCase(),q.value));render();$('#question').focus();const list=$('.transcript');list.scrollTop=list.scrollHeight}catch(err){message(err.message)}};q.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();form.requestSubmit()}};form.append(el('div','small','Ctrl / ⌘ + Enter to send'));w.append(form);
const help=el('details','help');help.append(el('summary',null,'Example questions'));const opts=el('div','intent-options');snap.intents.forEach(i=>opts.append(button(i.label,()=>{q.value=i.expressions[0];q.focus()})));help.append(paragraph('Select an intent to insert an example question. You can edit it before sending.','small'),opts);w.append(help)}
function reviewScreen(){const s=state.sessions.find(x=>x.id===reviewId)||active()||state.sessions.at(-1);const head=el('section','review-head');head.append(el('h1',null,'From questions to evidence'),paragraph('Review statements recorded in the conversation and choose goals for your next practice.'));main.append(head);if(!s){main.append(paragraph('No conversations yet. Choose a case to start your first practice.','empty'),button('Choose a case',()=>navigate('practice'),'primary'));return}reviewId=s.id;
const picker=el('select');picker.setAttribute('aria-label','Practice to review');state.sessions.slice().reverse().forEach((x)=>{const o=el('option',null,`${x.caseSnapshot.title} · ${new Date(x.createdAt).toLocaleString('en-US')} · ${x.turns.length} questions`);o.value=x.id;o.selected=x.id===s.id;picker.append(o)});picker.onchange=()=>{reviewId=picker.value;goalIds=new Set();render()};head.append(picker,paragraph(stamp(s.caseSnapshot)+' · authored responses','small'));
if(!s.turns.length)main.append(paragraph('There are no questions in this practice yet.','empty'));
const records=review(s);s.turns.forEach((t,i)=>{const row=el('section','review-row'),source=turnNode(t,i),note=el('aside','margin-note');note.id='note-'+t.id;note.tabIndex=-1;const related=records.filter(r=>r.asked.some(a=>a.turnId===t.id));note.append(el('span','evidence-label',`Evidence ${String(i+1).padStart(2,'0')}`));if(!t.evidence.length){note.append(el('h3',null,'No response linked yet'),paragraph('Return to practice and select the intended question to link a response.','small'))}else{note.append(el('h3',null,related.map(r=>r.label).join(' · ')));t.evidence.forEach(e=>{const fact=s.caseSnapshot.facts.find(f=>f.id===e.factId);const link=button('“'+e.quote+'”',()=>{document.querySelectorAll('.selected').forEach(n=>n.classList.remove('selected'));row.classList.add('selected');if(source.patientText){const at=t.patientResponse.indexOf(e.quote);source.patientText.replaceChildren(el('span',null,t.patientResponse.slice(0,at)),el('mark',null,e.quote),el('span',null,t.patientResponse.slice(at+e.quote.length)))}source.focus();source.scrollIntoView({block:'nearest'})},'evidence-link');note.append(link,paragraph(fact.value,'small'),paragraph(fact.status==='unknown'?'Patient reports not knowing':fact.status==='known-negative'?'Patient explicitly denies this item':'Information known to the patient','small'))});if(t.assisted)note.append(paragraph('Intent-selection assistance was used.','small'))}const toNote=button('View linked evidence',()=>{row.classList.add('selected');note.focus();note.scrollIntoView({block:'nearest'})},'evidence-link');source.append(toNote);row.append(source,note);main.append(row)});
const goals=el('section','goals');goals.append(el('h2',null,'Goals for the next practice'),paragraph('Choose 1–3 goals to restart with the same case and version. Previous records are retained.','small'));const opts=el('div','goal-options');records.forEach(r=>{const label=el('label'),input=el('input');input.type='checkbox';input.checked=goalIds.has(r.id);input.onchange=()=>{if(input.checked&&goalIds.size>=3){input.checked=false;message('You can select up to 3 practice goals.');return}input.checked?goalIds.add(r.id):goalIds.delete(r.id);retry.disabled=goalIds.size===0};label.append(input,el('span',null,r.label+(r.questionRecorded?' · question recorded':' · ask next time')));opts.append(label)});const retry=button('Retry with these goals',()=>{try{const next=retrySession(s,[...goalIds]);state.sessions.push(next);state.activeSessionId=next.id;selected=next.caseId;save();navigate('practice');$('#question')?.focus()}catch(e){message(e.message)}},'primary');retry.disabled=goalIds.size===0;goals.append(opts,retry);main.append(goals);
if(s.previousSessionId){const prev=state.sessions.find(x=>x.id===s.previousSessionId),comp=el('section','comparison');comp.append(el('h2',null,'Compare with previous practice'));s.goals.forEach(id=>{const data=compareSessions(prev,s,id),a=data.previous.item,b=data.current.item;comp.append(el('h3',null,b.label),paragraph(`Previous: ${a.asked.length} questions · Current: ${b.asked.length} questions`));for(const [name,session,item]of[['Previous',prev,a],['Current',s,b]]){const ev=item.facts.flatMap(f=>f.evidence);comp.append(paragraph(name+' Patient statement: '+(ev.length?ev.map(e=>'“'+e.quote+'”').join(' / '):'No linked statements'),'small'))}});main.append(comp)}}
function getDraft(){let d=state.drafts.find(x=>x.id===draftId);if(!d){d=state.drafts.find(x=>x.baseCaseId===selected);if(!d){d=cloneDraft(currentCase());state.drafts.push(d);save()}draftId=d.id}return d}
function editor(){const w=layout(),d=getDraft(),c=d.case;if(!Array.isArray(c.intents)||!c.intents.length||c.intents.some(i=>!i.response||!Array.isArray(i.expressions)||!Array.isArray(i.response.evidence))||!Array.isArray(c.facts)){w.append(el('h1',null,'Draft needs attention'),paragraph('This draft has no editable question or evidence structure. Export your records as JSON or create a new draft from the last published revision.'),button('Export JSON including drafts',()=>download(exportJSON(state),'cpx-draft-recovery.json')),button('New draft from last revision',()=>{const next=cloneDraft(currentCase());state.drafts.push(next);draftId=next.id;save();render()}));return}const columns=el('div','editor-layout'),form=el('div','editor-form'),preview=el('aside','editor-preview');form.append(el('h1',null,'Review and edit a case'),paragraph('Edit question expressions and authored responses, then save a new revision.','muted'),el('span','badge','Editing a copy'),paragraph(stamp(c),'small'));let errorBox=el('div','errors');errorBox.setAttribute('role','status');
function field(label,value,setter,multiline=false){const wrap=el('div','field'),l=el('label',null,label),n=el(multiline?'textarea':'input');n.id='field-'+Math.random().toString(36).slice(2);l.htmlFor=n.id;n.value=value??'';if(multiline)n.rows=3;n.oninput=()=>{setter(n.value);dirty=true;$('#save-state').textContent='Draft changes not saved';$('#draft-state').textContent='Unsaved changes';updatePreview()};wrap.append(l,n);return wrap}
form.append(el('h2',null,'Basic information'),field('Case title',c.title,v=>c.title=v),field('Patient opening line',c.description,v=>{c.description=v;if(c.opening_facts)c.opening_facts.patient_line=v},true),el('h2',null,'Response setup'));
const selector=el('select');selector.setAttribute('aria-label','Question intent to edit');c.intents.forEach((i,n)=>{const o=el('option',null,i.label);o.value=n;o.selected=n===selectedIntent;selector.append(o)});selector.onchange=()=>{selectedIntent=Number(selector.value);render()};form.append(selector);const i=c.intents[selectedIntent]||c.intents[0];form.append(field('Question intent',i.label,v=>{i.label=v;const check=c.checklist.find(x=>x.intentIds.includes(i.id));if(check)check.label=v}),field('Question expressions',i.expressions.join('\n'),v=>i.expressions=v.split('\n').filter(x=>x.trim()),true),paragraph('Enter one expression per line. Questions are matched exactly to registered expressions after normalization.','small'),field('Authored response',i.response.text,v=>i.response.text=v,true),el('h2',null,'Evidence linked to the response'));
i.response.evidence.forEach(e=>{const f=c.facts.find(f=>f.id===e.factId);form.append(field('Quoted passage',e.quote,v=>e.quote=v,true),field('Fact statement',f.value,v=>f.value=v,true));const wrap=el('div','field'),label=el('label',null,'Information status'),sel=el('select');sel.id='status-'+f.id;label.htmlFor=sel.id;for(const [v,t]of[['known-positive','Known information'],['known-negative','Patient explicitly denies this item'],['unknown','Information unknown to the patient']]){const o=el('option',null,t);o.value=v;o.selected=f.status===v;sel.append(o)}sel.onchange=()=>{f.status=sel.value;dirty=true;$('#save-state').textContent='Draft changes not saved';$('#draft-state').textContent='Unsaved changes'};wrap.append(label,sel);form.append(wrap)});
const actions=el('div','form-actions');actions.append(button('Validate structure',()=>{const errors=validateCase(c);errorBox.textContent=errors.length?'Items to check:\n'+errors.join('\n'):'Structure checked. You can save a new revision.'}),button('Save draft',()=>{if(save()){dirty=false;$('#draft-state').textContent='Draft saved on this device'}}),button('Publish new local revision',()=>{try{const next=publishDraft(d,state.cases);state.cases=next;if(save()){state.drafts=state.drafts.filter(x=>x.id!==d.id);save();draftId=null;dirty=false;navigate('practice');message('New revision saved. Existing practice sessions retain their previous version.')}}catch(e){errorBox.textContent='Please check before saving.\n'+e.message}},'primary'));form.append(errorBox,el('p','small',''),'');const draftStatus=el('p','small',dirty?'Unsaved changes':'Draft saved on this device');draftStatus.id='draft-state';form.append(draftStatus,actions);
function updatePreview(){preview.replaceChildren();const sticky=el('div','editor-sticky');sticky.append(el('h2',null,'Practice preview'),paragraph('Preview the selected question and response.','small'),illustration(),speech('Student',i.expressions[0]||'Enter a question expression.'),speech('Patient',i.response.text||'Enter a response.'),el('span','badge','Authored response'));preview.append(sticky)}updatePreview();columns.append(form,preview);w.append(columns)}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function about(){const box=el('div','info');box.append(el('h1',null,'My practice records'));const data=el('section');data.append(el('h2',null,'Save and transfer'),paragraph('Export cases, drafts, conversations, and practice goals as a JSON file to continue on another device.'));data.append(button('Export records as JSON',()=>{try{download(exportJSON(state),'cpx-practice-records.json')}catch(e){message(e.message)}}));const label=el('label',null,'Import records from JSON'),input=el('input');input.type='file';input.accept='.json,application/json';input.id='import-file';label.htmlFor=input.id;input.onchange=async()=>{if(!input.files[0])return;try{if(input.files[0].size>10000000)throw Error('Choose a file of 10 MB or less.');const text=await input.files[0].text();if(!confirm('Replace current records with the imported file? Export current records first if you want to restore them later.'))return;const ok=store.import(text);if(ok===false)throw Error(store.error||'Saving failed.');state=store.state;selected=latestCases()[0]?.id;draftId=null;message('Records imported.');render()}catch(e){message('Import failed. Existing records are retained. '+e.message)}finally{input.value=''}};const f=el('div','field');f.append(label,input);data.append(f,paragraph('Saved in this browser on this device. There is no automatic sync.','small'));box.append(data);
const history=el('section','session-list');history.append(el('h2',null,'Practice history'));if(!state.sessions.length)history.append(paragraph('Your first practice will appear here.'));state.sessions.slice().reverse().forEach(s=>history.append(button(`${s.caseSnapshot.title} · ${s.turns.length} questions · ${stamp(s.caseSnapshot)}`,()=>{state.activeSessionId=s.id;selected=s.caseId;save();navigate('practice')})));box.append(history);
const project=el('section');project.append(el('h2',null,'About this workbench'),paragraph('An educational workbench where medical students practice interviews with fictional cases and review their questions and patient statements.'),paragraph('The current prototype uses authored case responses. Claude integration is planned.'),paragraph('The three cases and their dialogues are original fictional content. Review recorded questions alongside quoted evidence.','small'),paragraph('Response mode: '+MODE+' · App 2.0.0 · Case source '+(currentCase()?.sourceMetadata?.content_version||'2026-10-08.2'),'small'));box.append(project);main.append(box)}
function render(){document.querySelector('header')?.classList.toggle('is-project-header',view==='project');updateLanguageLinks();document.querySelector('.guided-demo')?.destroyGuidedDemo?.();main.replaceChildren();main.className=view==='project'?'project-main':'';document.querySelectorAll('[data-nav]').forEach(b=>{const yes=b.dataset.nav===view;b.classList.toggle('active',yes);b.setAttribute('aria-current',yes?'page':'false')});try{({project,practice,review:reviewScreen,editor,about}[view])()}catch(e){main.append(paragraph('Could not open this screen. '+e.message,'errors'));console.error(e)}$('#save-state').textContent=store.error?'Kept in this tab':'Saved on this device'}
window.addEventListener('beforeunload',e=>{if(dirty||store.error){e.preventDefault();e.returnValue=''}});
try{const source=await fetch('./casebank.en.json').then(r=>{if(!r.ok)throw Error('Could not read the case file.');return r.json()});projectCases=adaptCaseBank(source);if(!state.cases.length){const cases=projectCases;if(store.seed){store.seed(cases);state=store.state}else{state.cases=cases;if(!store.error)save()}}selected=latestCases()[0]?.id;if(active())selected=active().caseId;message(store.error||'');render()}catch(e){message('Could not start. '+e.message);main.append(button('Reload',()=>location.reload()))}
