import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{frontCopy as en}from'../project-front/copy-en.mjs';import{frontCopy as ko}from'../project-front/copy-ko.mjs';import{renderIntroduction,renderDemoIntroduction,renderFoundation,languageTarget,isProjectAnchor}from'../project-front/render.mjs';
class E{constructor(tag){this.tagName=tag;this.children=[];this.attributes={};this.listeners={};this.textContent='';this.className=''}append(...n){this.children.push(...n)}setAttribute(k,v){this.attributes[k]=v}addEventListener(k,f){this.listeners[k]=f}}
globalThis.document={createElement:t=>new E(t)};const all=n=>[n,...n.children.flatMap(all)];
for(const copy of[en,ko]){
 test(copy.lang+': introduction renders exact identity, purpose, concise sections and accessible practice action',()=>{let view;const root=renderIntroduction(copy,{navigate:v=>view=v}),nodes=all(root);for(const t of[copy.headline,copy.lead,copy.byline,...copy.opening.flatMap(part=>[part.title,...part.paragraphs])])assert.ok(nodes.some(n=>n.textContent===t),t);assert.equal(nodes.filter(n=>n.className==='front-loop-rail')[0].children.length,4);nodes.find(n=>n.textContent===copy.secondary).listeners.click();assert.equal(view,'practice');assert.equal(nodes.find(n=>n.textContent===copy.primary+' ↓').href,'#project-demo')});
 test(copy.lang+': API roles, 30 planned scenarios and support request are exact and not duplicated with generic plan',()=>{const root=renderFoundation(copy,{navigate(){}}),nodes=all(root);for(const t of[copy.portfolio.title,copy.portfolio.lead,...copy.portfolio.roles.flatMap(r=>[r.title,r.text]),copy.portfolio.support])assert.ok(nodes.some(n=>n.textContent===t),t);assert.ok(!nodes.some(n=>n.textContent===copy.planned));assert.ok(nodes.some(n=>n.textContent===copy.working));assert.ok(copy.portfolio.roles[2].text.includes('30'))});
}
test('English is the default entry and visible language links preserve the selected workbench view',()=>{const root=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.ok(root.includes('0;url=./en/index.html'));for(const view of['project','practice','review','editor','about'])assert.equal(languageTarget('ko','#'+view),'../site/index.html?v=cpx-20261009-1436#'+view);assert.equal(languageTarget('en','#gd-turn-8'),'../en/index.html?v=cpx-20261009-1436#project');for(const folder of['en','site']){const html=fs.readFileSync(new URL('../'+folder+'/index.html',import.meta.url),'utf8');assert.ok(html.includes('class="locale-switch"'));assert.ok(html.includes('data-language="en"'));assert.ok(html.includes('data-language="ko"'))}});
test('project presentation places introduction before demo and portfolio after demo without repeated introductory notices',()=>{for(const folder of['en','site']){const s=fs.readFileSync(new URL('../'+folder+'/presentation.mjs',import.meta.url),'utf8');assert.ok(s.includes('page.append(renderIntroduction(frontCopy,{navigate}),renderDemoIntroduction(frontCopy),renderGuidedDemo(demoData,{showIntro:false}),renderFoundation(frontCopy,{navigate}))'))}const demo=fs.readFileSync(new URL('../guided-demo/runtime.mjs',import.meta.url),'utf8');assert.ok(demo.includes('Voice-input example'));assert.ok(!demo.includes('fetch('))});

test('native project anchors bypass workbench routing while real workbench views remain routes',()=>{for(const h of ['#overview','#project-demo','#why-claude','#gd-turn-8','#gd-evaluation'])assert.equal(isProjectAnchor(h),true);for(const h of ['#project','#practice','#review','#editor','#about','#unknown'])assert.equal(isProjectAnchor(h),false);for(const folder of ['en','site']){const app=fs.readFileSync(new URL('../'+folder+'/app.mjs',import.meta.url),'utf8');assert.ok(app.includes("if(isProjectAnchor(window.location?.hash))"));const html=fs.readFileSync(new URL('../'+folder+'/index.html',import.meta.url),'utf8');assert.ok(html.includes('class="is-project-header"'));assert.ok(html.includes('class="project-reviewer-nav"'))}});

for(const copy of [en,ko]){
 test(copy.lang+': three concise sections preserve CPX, practice and future API intent',()=>{const nodes=all(renderIntroduction(copy,{navigate(){}}));assert.equal(copy.opening.length,3);assert.ok(copy.opening.every(s=>s.paragraphs.length===2));assert.ok(copy.opening[0].paragraphs[0].includes('Clinical Performance Examination'));const order=copy.opening.map(s=>nodes.findIndex(n=>n.textContent===s.title));assert.ok(order.every((v,i)=>v>=0&&(i===0||v>order[i-1])));const api=copy.opening[2].paragraphs.join(' ');assert.ok(api.includes('Claude API'));assert.ok(api.includes(copy.lang==='en'?'next step':'다음 단계'));});
 test(copy.lang+': opening stays under one third of previous rendered length without small-print boilerplate',()=>{const nodes=all(renderIntroduction(copy,{navigate(){}})),text=nodes.map(n=>n.textContent).filter(Boolean).join('\n'),previous=copy.lang==='ko'?6031:11773;assert.ok(text.length<previous/3,`${text.length}/${previous}`);for(const phrase of ['직접 작성한 교육용 예시','Original educational illustrations','Originally developed in Korean. English translation for review.'])assert.ok(!text.includes(phrase));assert.equal(nodes.filter(n=>n.className==='front-section-sources').length,2);for(const s of copy.opening)for(const source of s.sources){const a=nodes.find(n=>n.textContent===source.label);assert.equal(a.href,source.url);assert.equal(a.tagName,'a')}assert.equal(nodes.filter(n=>n.tagName==='h2').length,3);});
 test(copy.lang+': demonstration retains one clear prewritten versus live status at entry',()=>{const nodes=all(renderDemoIntroduction(copy));assert.equal(nodes.filter(n=>n.textContent===copy.demoStatus).length,1);assert.ok(copy.demoStatus.includes(copy.lang==='en'?'no live API':'API 연결 전'));const intro=all(renderIntroduction(copy,{navigate(){}}));assert.ok(!intro.some(n=>n.textContent===copy.demoStatus));});
}

test('HTML entry and schema-coupled module imports use one cache version in both languages',()=>{const v='cpx-20261009-1436';for(const folder of ['en','site']){const html=fs.readFileSync(new URL('../'+folder+'/index.html',import.meta.url),'utf8');assert.ok(html.includes('src="./app.mjs?v='+v+'"'));const app=fs.readFileSync(new URL('../'+folder+'/app.mjs',import.meta.url),'utf8');for(const path of ['./presentation.mjs','../project-front/render.mjs'])assert.ok(app.includes(path+'?v='+v));const presentation=fs.readFileSync(new URL('../'+folder+'/presentation.mjs',import.meta.url),'utf8');for(const path of ['../project-front/render.mjs','../project-front/copy-'+(folder==='site'?'ko':'en')+'.mjs','../guided-demo/runtime.mjs'])assert.ok(presentation.includes(path+'?v='+v));}const renderer=fs.readFileSync(new URL('../project-front/render.mjs',import.meta.url),'utf8');assert.ok(!renderer.includes('copy.education'));assert.ok(!renderer.includes('copy.narrative'));});
