import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{frontCopy as en}from'../project-front/copy-en.mjs';import{frontCopy as ko}from'../project-front/copy-ko.mjs';import{renderIntroduction,renderDemoIntroduction,renderFoundation,languageTarget,isProjectAnchor}from'../project-front/render.mjs';
class E{constructor(tag){this.tagName=tag;this.children=[];this.attributes={};this.listeners={};this.textContent='';this.className=''}append(...n){this.children.push(...n)}setAttribute(k,v){this.attributes[k]=v}addEventListener(k,f){this.listeners[k]=f}}
globalThis.document={createElement:t=>new E(t)};const all=n=>[n,...n.children.flatMap(all)];
for(const copy of[en,ko]){
 test(copy.lang+': introduction renders exact identity, purpose, four steps and accessible practice action',()=>{let view;const root=renderIntroduction(copy,{navigate:v=>view=v}),nodes=all(root);for(const t of[copy.headline,copy.lead,copy.byline,copy.languageNote,...Object.values(copy.narrative).flatMap(part=>[part.title,...part.paragraphs]),...copy.loop])assert.ok(nodes.some(n=>n.textContent===t),t);assert.equal(copy.loop.length,4);nodes.find(n=>n.textContent===copy.secondary).listeners.click();assert.equal(view,'practice');assert.equal(nodes.find(n=>n.textContent===copy.primary+' ↓').href,'#project-demo')});
 test(copy.lang+': API roles, 30 planned scenarios and support request are exact and not duplicated with generic plan',()=>{const root=renderFoundation(copy,{navigate(){}}),nodes=all(root);for(const t of[copy.portfolio.title,copy.portfolio.lead,...copy.portfolio.roles.flatMap(r=>[r.title,r.text]),copy.portfolio.example,copy.portfolio.support,copy.portfolio.stage,copy.creator])assert.ok(nodes.some(n=>n.textContent===t),t);assert.ok(!nodes.some(n=>n.textContent===copy.planned));assert.ok(nodes.some(n=>n.textContent===copy.working));assert.ok(copy.portfolio.roles[2].text.includes('30'))});
}
test('English is the default entry and visible language links preserve the selected workbench view',()=>{const root=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.ok(root.includes('0;url=./en/index.html'));for(const view of['project','practice','review','editor','about'])assert.equal(languageTarget('ko','#'+view),'../site/index.html#'+view);assert.equal(languageTarget('en','#gd-turn-8'),'../en/index.html#project');for(const folder of['en','site']){const html=fs.readFileSync(new URL('../'+folder+'/index.html',import.meta.url),'utf8');assert.ok(html.includes('class="locale-switch"'));assert.ok(html.includes('data-language="en"'));assert.ok(html.includes('data-language="ko"'))}});
test('project presentation places introduction before demo and portfolio after demo without modifying its runtime',()=>{for(const folder of['en','site']){const s=fs.readFileSync(new URL('../'+folder+'/presentation.mjs',import.meta.url),'utf8');assert.ok(s.includes('page.append(renderIntroduction(frontCopy,{navigate}),renderDemoIntroduction(frontCopy),renderGuidedDemo(demoData),renderFoundation(frontCopy,{navigate}))'))}const demo=fs.readFileSync(new URL('../guided-demo/runtime.mjs',import.meta.url),'utf8');assert.ok(demo.includes('Voice-input example'));assert.ok(!demo.includes('fetch('))});

test('native project anchors bypass workbench routing while real workbench views remain routes',()=>{for(const h of ['#overview','#project-demo','#why-claude','#gd-turn-8','#gd-evaluation'])assert.equal(isProjectAnchor(h),true);for(const h of ['#project','#practice','#review','#editor','#about','#unknown'])assert.equal(isProjectAnchor(h),false);for(const folder of ['en','site']){const app=fs.readFileSync(new URL('../'+folder+'/app.mjs',import.meta.url),'utf8');assert.ok(app.includes("if(isProjectAnchor(window.location?.hash))"));const html=fs.readFileSync(new URL('../'+folder+'/index.html',import.meta.url),'utf8');assert.ok(html.includes('class="is-project-header"'));assert.ok(html.includes('class="project-reviewer-nav"'))}});

for(const copy of [en,ko]){
 test(copy.lang+': editorial opening explains exam, practice need, and planned API in order',()=>{const root=renderIntroduction(copy,{navigate(){}}),nodes=all(root),n=copy.narrative;assert.ok(n.exam.paragraphs[0].includes('Clinical Performance Examination'));const source=nodes.find(x=>x.textContent===copy.sourceLabel);assert.equal(source.href,'https://medicine.gachon.ac.kr/sub01_about/page04_02_t02.php');for(const text of [n.exam.scope,n.challenge.reflection,n.bridge.transition])assert.ok(nodes.some(x=>x.textContent===text));const ordered=[copy.lead,n.exam.title,n.challenge.title,n.purpose.title,copy.loopTitle,n.bridge.title,n.bridge.transition].map(t=>nodes.findIndex(x=>x.textContent===t));assert.ok(ordered.every((v,i)=>v>=0&&(i===0||v>ordered[i-1])));assert.ok(n.bridge.paragraphs[1].includes('Claude API'));assert.ok(n.bridge.paragraphs[0].includes(copy.lang==='en'?'not connected yet':'아직 연결하지 않았습니다'));});
 test(copy.lang+': opening example is an exact fictional demo exchange, with a readable retry',async()=>{const {demoData}=await import('../'+(copy.lang==='en'?'en':'site')+'/demo-data.mjs');const raw=JSON.stringify(demoData);for(const text of [copy.apiExample.question,copy.apiExample.patient])assert.ok(raw.includes(text));const nodes=all(renderIntroduction(copy,{navigate(){}}));for(const text of [copy.apiExample.question,copy.apiExample.patient,copy.apiExample.alternative])assert.equal(nodes.filter(n=>n.textContent===text).length,1);assert.ok(nodes.some(n=>n.tagName==='figcaption'&&n.textContent===copy.narrative.challenge.exampleLabel));});
}
