import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{frontCopy as en}from'../project-front/copy-en.mjs';import{frontCopy as ko}from'../project-front/copy-ko.mjs';import{renderIntroduction,renderDemoIntroduction,renderFoundation,languageTarget,isProjectAnchor}from'../project-front/render.mjs';
class E{constructor(tag){this.tagName=tag;this.children=[];this.attributes={};this.listeners={};this.textContent='';this.className=''}append(...n){this.children.push(...n)}setAttribute(k,v){this.attributes[k]=v}addEventListener(k,f){this.listeners[k]=f}}
globalThis.document={createElement:t=>new E(t)};const all=n=>[n,...n.children.flatMap(all)];
for(const copy of[en,ko]){
 test(copy.lang+': introduction renders exact identity, purpose, four steps and accessible practice action',()=>{let view;const root=renderIntroduction(copy,{navigate:v=>view=v}),nodes=all(root);for(const t of[copy.headline,copy.lead,copy.byline,copy.languageNote,copy.storyTitle,...copy.paragraphs,...copy.loop])assert.ok(nodes.some(n=>n.textContent===t),t);assert.equal(copy.loop.length,4);nodes.find(n=>n.textContent===copy.secondary).listeners.click();assert.equal(view,'practice');assert.equal(nodes.find(n=>n.textContent===copy.primary+' ↓').href,'#project-demo')});
 test(copy.lang+': API roles, 30 planned scenarios and support request are exact and not duplicated with generic plan',()=>{const root=renderFoundation(copy,{navigate(){}}),nodes=all(root);for(const t of[copy.portfolio.title,copy.portfolio.lead,...copy.portfolio.roles.flatMap(r=>[r.title,r.text]),copy.portfolio.example,copy.portfolio.support,copy.portfolio.stage,copy.creator])assert.ok(nodes.some(n=>n.textContent===t),t);assert.ok(!nodes.some(n=>n.textContent===copy.planned));assert.ok(nodes.some(n=>n.textContent===copy.working));assert.ok(copy.portfolio.roles[2].text.includes('30'))});
}
test('English is the default entry and visible language links preserve the selected workbench view',()=>{const root=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.ok(root.includes('0;url=./en/index.html'));for(const view of['project','practice','review','editor','about'])assert.equal(languageTarget('ko','#'+view),'../site/index.html#'+view);assert.equal(languageTarget('en','#gd-turn-8'),'../en/index.html#project');for(const folder of['en','site']){const html=fs.readFileSync(new URL('../'+folder+'/index.html',import.meta.url),'utf8');assert.ok(html.includes('class="locale-switch"'));assert.ok(html.includes('data-language="en"'));assert.ok(html.includes('data-language="ko"'))}});
test('project presentation places introduction before demo and portfolio after demo without modifying its runtime',()=>{for(const folder of['en','site']){const s=fs.readFileSync(new URL('../'+folder+'/presentation.mjs',import.meta.url),'utf8');assert.ok(s.includes('page.append(renderIntroduction(frontCopy,{navigate}),renderDemoIntroduction(frontCopy),renderGuidedDemo(demoData),renderFoundation(frontCopy,{navigate}))'))}const demo=fs.readFileSync(new URL('../guided-demo/runtime.mjs',import.meta.url),'utf8');assert.ok(demo.includes('Voice-input example'));assert.ok(!demo.includes('fetch('))});

test('native project anchors bypass workbench routing while real workbench views remain routes',()=>{for(const h of ['#overview','#project-demo','#why-claude','#gd-turn-8','#gd-evaluation'])assert.equal(isProjectAnchor(h),true);for(const h of ['#project','#practice','#review','#editor','#about','#unknown'])assert.equal(isProjectAnchor(h),false);for(const folder of ['en','site']){const app=fs.readFileSync(new URL('../'+folder+'/app.mjs',import.meta.url),'utf8');assert.ok(app.includes("if(isProjectAnchor(window.location?.hash))"));const html=fs.readFileSync(new URL('../'+folder+'/index.html',import.meta.url),'utf8');assert.ok(html.includes('class="is-project-header"'));assert.ok(html.includes('class="project-reviewer-nav"'))}});
