import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {demoData as ko} from '../site/demo-data.mjs';import {demoData as en} from '../en/demo-data.mjs';import {coveredDomains,scrollRevealProgress,activeTurnAt,establishedFacts,renderGuidedDemo,graphemes,transcriptionProgress,responseGate,transcribedText} from '../guided-demo/runtime.mjs';
for(const data of [ko,en]){
 test(data.lang+': full example contains twelve exact student/SP exchanges',()=>{assert.equal(data.turns.length,12);assert.ok(data.turns.every(t=>t.student&&t.patient));assert.equal(data.liveAPI,false);assert.equal(data.scripted,true)});
 test(data.lang+': 10/12 coverage derives from actual IDs and evidence, not a fake model score',()=>{const domains=coveredDomains(data);assert.equal(domains.filter(d=>d.addressed).length,10);assert.deepEqual(domains.filter(d=>!d.addressed).map(d=>d.id.split('.').at(-1)),['q09','q12']);assert.equal(coveredDomains({...data,turns:data.turns.filter(t=>!t.questionId?.endsWith('q07'))}).filter(d=>d.addressed).length,9)});
 test(data.lang+': sticky summary rewinds and never discloses future or omitted facts',()=>{assert.equal(establishedFacts(data,-1).length,0);for(let i=0;i<12;i++){const facts=establishedFacts(data,i);assert.deepEqual(facts,data.turns.slice(0,i+1).flatMap(t=>t.facts));assert.ok(!facts.some(f=>f.id.endsWith('f15')||f.id.endsWith('f18')))}assert.ok(establishedFacts(data,7).some(f=>f.id.endsWith('f12')));assert.ok(!establishedFacts(data,6).some(f=>f.id.endsWith('f12')))});
 test(data.lang+': mistaken coffee premise is corrected and unknown observation is not negative',()=>{assert.ok(data.turns[7].questionId.endsWith('q07'));assert.ok(data.turns[7].facts[0].id.endsWith('f12'));assert.equal(data.turns[10].facts[0].status,'patient_unknown');assert.ok(coveredDomains(data).find(d=>d.id.endsWith('q11')).addressed)});
 test(data.lang+': source-linked feedback quotes really occur in the dialogue',()=>{for(const f of data.labels.feedbackItems)assert.ok(data.turns[f.turn-1].student.includes(f.quote));assert.ok(data.turns[8].student.includes(data.labels.goodQuote));assert.equal(data.labels.goalItems.length,2)});
}
class E{constructor(tag){this.tagName=tag;this.children=[];this.attributes={};this.listeners={};this.style={setProperty(k,v){this[k]=v}};this.textContent='';this.top=100;this.className=''}append(...n){this.children.push(...n)}replaceChildren(...n){this.children=n}setAttribute(k,v){this.attributes[k]=String(v)}addEventListener(k,f){this.listeners[k]=f}removeEventListener(k){delete this.listeners[k]}getBoundingClientRect(){return{top:this.top+(this._gdOffset||0)}}querySelector(s){return walk(this).find(n=>n.className?.split(' ').includes(s.slice(1)))}}
function walk(n){return[n,...n.children.flatMap(walk)]}
function harness(fn,reduced=false){const originals={document:globalThis.document,window:globalThis.window};globalThis.document={createElement:t=>new E(t)};globalThis.window={innerHeight:1000,matchMedia:()=>({matches:reduced}),addEventListener(k,f){this[k]=f},removeEventListener(k){delete this[k]}};try{const root=renderGuidedDemo(ko);fn({root,all:()=>walk(root)})}finally{Object.assign(globalThis,originals)}}
test('native scroll progress reverses, clamps and never fades prior content above viewport',()=>{assert.equal(scrollRevealProgress(1100,1000),0);assert.equal(scrollRevealProgress(-400,1000),1);assert.ok(scrollRevealProgress(700,1000)>scrollRevealProgress(850,1000));assert.equal(activeTurnAt([100,600,900],1000),1);assert.equal(activeTurnAt([800,1100],1000),-1)});
test('all twelve chronological conversations stay in DOM; meaningful source anchors resolve',()=>harness(({root,all})=>{assert.equal(all().filter(n=>n.className==='gd-scroll-turn').length,12);const ids=new Set(all().map(n=>n.id).filter(Boolean));for(const n of all().filter(n=>n.href?.startsWith('#')))assert.ok(ids.has(n.href.slice(1)));assert.ok(all().some(n=>n.textContent==='10 / 12'));assert.equal(root.guidedDemoState().mode,'native-scroll')}));
test('mid-scroll refresh/update selects current facts and reverse scroll clears future summary',()=>harness(({root,all})=>{const responses=all().filter(n=>n.className.includes('gd-patient'));responses.forEach((n,i)=>n.top=i<8?100:1200);root.updateGuidedDemo();assert.equal(root.guidedDemoState().activeTurn,7);responses.forEach(n=>n.top=1200);root.updateGuidedDemo();assert.equal(root.guidedDemoState().activeTurn,-1);const summary=all().find(n=>n.className==='gd-live-facts');assert.ok(walk(summary).some(n=>n.textContent===ko.labels.noFacts))}));
test('reduced motion keeps all text opaque without translation; manual reading mode also works',()=>{harness(({root,all})=>{all().forEach(n=>n.top=1800);root.updateGuidedDemo();const patient=all().find(n=>n.className.includes('gd-patient'));assert.equal(patient.style.opacity,'1');assert.equal(patient.style.transform,'translateY(0px)')},true);harness(({root,all})=>{all().forEach(n=>n.top=1800);const toggle=all().find(n=>n.className==='gd-read-mode');toggle.listeners.click();assert.equal(root.guidedDemoState().staticMode,true);assert.equal(all().find(n=>n.className.includes('gd-patient')).style.opacity,'1')})});
test('renderer has no timers, forced scrolling, network, input interception or storage changes',()=>{const source=fs.readFileSync(new URL('../guided-demo/runtime.mjs',import.meta.url),'utf8');for(const forbidden of ['setTimeout','setInterval','fetch(','localStorage','scrollTo(','scrollIntoView(','preventDefault(','wheel','touchmove'])assert.ok(!source.includes(forbidden),forbidden);assert.ok(source.includes("'scroll',onScroll,{passive:true}"));assert.deepEqual(en.turns.map(t=>t.questionId),ko.turns.map(t=>t.questionId))});

test('Korean graphemes, combining marks and emoji are never split mid-cluster',()=>{assert.deepEqual(graphemes('한글'),['한','글']);assert.equal(graphemes('한').length,1);assert.equal(graphemes('e\u0301').length,1);assert.equal(graphemes('👩‍⚕️').length,1);assert.equal(transcribedText('한글?',1),'한글?')});
test('question finishes before any SP response reveal and reverse scroll restores partial text',()=>{for(const base of [0,.1,.4,.69]){assert.ok(transcriptionProgress(base)<1);assert.equal(responseGate(base),0)}assert.equal(transcriptionProgress(.7),1);assert.equal(responseGate(.7),0);assert.ok(responseGate(.8)>0);assert.ok(transcribedText('어떤 점이 불편하세요?',.3).length<transcribedText('어떤 점이 불편하세요?',.8).length)});
test('partial transcription reserves full accessible question and hides only visual SP layer',()=>harness(({root,all})=>{const student=all().find(n=>n.className.includes('gd-student'));student.top=800;root.updateGuidedDemo();const t=student._transcription;assert.ok(t.count>0&&t.count<t.parts.length);assert.equal(t.source.textContent,ko.turns[0].student);assert.equal(t.overlay.attributes['aria-hidden'],'true');assert.equal(all().find(n=>n.className.includes('gd-patient')).style.opacity,'0');assert.ok(!student.style.height);assert.ok(!student.style.maxHeight)}));
test('reduced motion displays complete source text and a quiet waveform',()=>harness(({root,all})=>{const student=all().find(n=>n.className.includes('gd-student'));student.top=1900;root.updateGuidedDemo();const t=student._transcription;assert.equal(t.count,t.parts.length);assert.equal(t.overlay.style.display,'none');assert.equal(t.source.style.color,'inherit');assert.ok(t.bars.every(b=>b.style.height==='3px'))},true));
test('voice-input affordance is clearly simulated and never requests microphone or speech services',()=>{const src=fs.readFileSync(new URL('../guided-demo/runtime.mjs',import.meta.url),'utf8');assert.ok(src.includes('음성 입력 예시'));for(const forbidden of ['getUserMedia','MediaRecorder','SpeechRecognition','speechSynthesis','AudioContext','navigator.mediaDevices'])assert.ok(!src.includes(forbidden))});
