import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {webcrypto} from 'node:crypto';
const source=JSON.parse(fs.readFileSync(new URL('../../site/casebank.ko.json',import.meta.url)));
class Element{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.attributes={};this.listeners={};this.className='';this.textContent='';this.value='';this.style={};this.classList={add:c=>{this.className+=' '+c},remove:c=>{this.className=this.className.split(' ').filter(x=>x!==c).join(' ')},toggle:(c,y)=>y?this.classList.add(c):this.classList.remove(c)};}append(...xs){this.children.push(...xs.filter(x=>x instanceof Element))}replaceChildren(...xs){this.children=[];this.append(...xs)}setAttribute(k,v){this.attributes[k]=v}addEventListener(k,v){this.listeners[k]=v}focus(){document.activeElement=this}scrollIntoView(){}click(){if(this.disabled)return;this.listeners.click?.({target:this});this.onclick?.({target:this})}requestSubmit(){this.onsubmit?.({preventDefault(){}})}}
let memory=new Map();const header=new Element('header'),main=new Element('main'),notice=new Element('div'),save=new Element('span');main.id='main';notice.id='notice';save.id='save-state';const roots=[header,main,notice,save];for(const view of ['project','practice','review','editor','about']){const b=new Element('button');b.dataset={nav:view};header.append(b)}
function all(){const out=[];function visit(n){out.push(n);n.children.forEach(visit)}roots.forEach(visit);return out}function matches(n,s){if(s.startsWith('#'))return n.id===s.slice(1);if(s.startsWith('.'))return n.className.split(' ').includes(s.slice(1));if(s==='[data-nav]')return !!n.dataset?.nav;return n.tagName===s.toUpperCase()}
globalThis.document={createElement:t=>new Element(t),querySelector:s=>all().find(n=>matches(n,s)),querySelectorAll:s=>all().filter(n=>matches(n,s)),activeElement:null};const events={};globalThis.window={location:{hash:''},history:{pushState(a,b,hash){window.location.hash=hash}},addEventListener(name,fn){events[name]=fn}};globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};globalThis.fetch=async()=>({ok:true,json:async()=>source});globalThis.confirm=()=>true;globalThis.crypto??=webcrypto;
await import('../../site/app.mjs');const nodes=(tag)=>all().filter(n=>n.tagName===tag.toUpperCase());const btn=text=>nodes('button').find(n=>n.textContent===text);const nav=v=>header.children.find(n=>n.dataset.nav===v).click();const stored=()=>JSON.parse([...memory.values()][0]);const question=()=>document.querySelector('#question');
test('project is default and presentation actions preserve stored data',()=>{assert.ok(all().some(n=>n.className==='project-title'));assert.equal(stored().sessions.length,0);const cases=structuredClone(stored().cases);btn('이 증례로 연습 ↗').click();assert.equal(window.location.hash,'#practice');assert.deepEqual(stored().cases,cases);assert.equal(stored().sessions.length,0)});
test('UI seeds all three real cases and displays source version',()=>{assert.equal(stored().cases.length,3);assert.ok(all().some(n=>n.textContent.includes('원본 1.1.0')))});
test('start and keyboard submit preserve every unmatched turn',()=>{btn('새 연습 시작').click();assert.ok(question());question().value='UI unmatched';question().onkeydown({ctrlKey:true,key:'Enter',preventDefault(){}});assert.equal(stored().sessions[0].turns.length,1);assert.equal(stored().sessions[0].turns[0].patientResponse,null)});
test('intent assistance requires an explicit button and links saved source',()=>{btn('시작과 경과').click();let s=stored().sessions[0];assert.equal(s.turns.length,2);assert.equal(s.turns[1].assisted,true);assert.equal(s.turns[1].assistanceForTurnId,s.turns[0].id)});
test('repeated typed exact questions are retained',()=>{for(let i=0;i<2;i++){question().value=source.cases[0].intent_questions[0].question;question().onkeydown({ctrlKey:true,key:'Enter',preventDefault(){}})}let turns=stored().sessions[0].turns;assert.equal(turns.length,4);assert.equal(turns[2].patientResponse,turns[3].patientResponse)});
test('review links focus real saved sources',()=>{btn('연습 마치기').click();assert.ok(btn('연결 근거 보기'));btn('연결 근거 보기').click();assert.ok(document.activeElement.id.startsWith('note-'));assert.ok(all().some(n=>n.textContent.includes(source.cases[0].fact_units[0].statement)))});
test('clicking exact evidence marks only a saved patient quote',()=>{const quote=source.cases[0].intent_questions[0].revealed_fact_evidence[0].answer_quote;btn('“'+quote+'”').click();assert.equal(nodes('mark')[0].textContent,quote);assert.ok(document.activeElement.id.startsWith('turn-'))});
test('goal checkbox permits keyboard-equivalent activation and retry exact snapshot',()=>{const check=nodes('input').find(n=>n.type==='checkbox');check.checked=true;check.onchange();btn('이 목표로 다시 연습').click();const s=stored().sessions;assert.equal(s.length,2);assert.deepEqual(s[0].caseSnapshot,s[1].caseSnapshot);assert.equal(s[1].goals.length,1);assert.ok(question())});
test('editor first save and subsequent save retain field edits',()=>{nav('editor');let title=nodes('input').find(n=>n.value===source.cases[0].title);title.value='수정한 연습 제목';title.oninput();btn('초안 저장').click();assert.equal(stored().drafts[0].case.title,'수정한 연습 제목');title.value='두 번째 수정 제목';title.oninput();btn('초안 저장').click();assert.equal(stored().drafts[0].case.title,'두 번째 수정 제목')});
test('publishing new revision preserves old active session',()=>{btn('새 편집본 게시').click();const s=stored();assert.equal(s.cases.length,4);assert.equal(s.cases.at(-1).version,2);assert.equal(s.cases.at(-1).sourceVersion,'1.1.0');assert.equal(s.sessions[1].caseSnapshot.title,source.cases[0].title);assert.equal(s.drafts.length,0)});
test('new practice uses newest revision',()=>{btn('새 연습').click();const s=stored();assert.equal(s.sessions.at(-1).caseVersion,2);assert.equal(s.sessions.at(-1).caseSnapshot.title,'두 번째 수정 제목')});
test('about development status appears once and no server API fetch exists',()=>{nav('about');assert.equal(all().filter(n=>n.textContent.includes('Claude 연동은 개발 중')).length,1);const app=fs.readFileSync(new URL('../../site/app.mjs',import.meta.url),'utf8');assert.ok(!app.includes('innerHTML'));assert.equal((app.match(/fetch\(/g)||[]).length,1)});

test('hash navigation restores project and review without replacing records',()=>{const before=structuredClone(stored());window.location.hash='#project';events.hashchange();assert.ok(all().some(n=>n.className==='project-title'));window.location.hash='#review';events.popstate();assert.ok(all().some(n=>n.textContent==='질문에서 근거로'));assert.deepEqual(stored(),before);nav('project');btn('연습 화면 살펴보기 →').click();assert.equal(window.location.hash,'#practice');assert.deepEqual(stored(),before)});

test('project renders approved creator and plan text exactly once without altering records',async()=>{
 const {identity}=await import('../../site/identity.mjs');const before=structuredClone(stored());nav('project');
 for(const value of [identity.creator,identity.creatorContext,identity.started,identity.introduction,identity.planIntro,identity.english,...identity.plans.flat()])assert.equal(all().filter(n=>n.textContent===value).length,1,value);
 assert.ok(all().some(n=>n.textContent==='만드는 사람'));assert.ok(all().some(n=>n.textContent==='개발 계획'));
 assert.ok(all().some(n=>n.attributes.lang==='en'));
 assert.deepEqual(stored(),before);
 const html=fs.readFileSync(new URL('../../site/index.html',import.meta.url),'utf8');
 for(const value of [identity.creator,identity.creatorContext,identity.started,identity.introduction,identity.planIntro,identity.english,...identity.plans.flat()])assert.ok(html.includes(value),value);
 assert.equal(all().filter(n=>n.textContent.includes('Claude 연동은 개발 중')).length,0);
 nav('about');assert.equal(all().filter(n=>n.textContent.includes('Claude 연동은 개발 중')).length,1);
});
