// Scripted, native-scroll walkthrough. No timers, network calls, or practice-store access.
const el=(tag,cls,value)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(value!==undefined)n.textContent=value;return n};
const p=(value,cls='')=>el('p',cls,value);
export function coveredDomains(data){const ids=new Set(data.turns.filter(t=>t.questionId&&t.facts.length&&t.patient).map(t=>t.questionId));return data.domains.map(d=>({...d,addressed:ids.has(d.id)}))}
export function scrollRevealProgress(top,height){return Math.max(0,Math.min(1,(height*.92-top)/(height*.34)))}
export function graphemes(value){if(typeof Intl.Segmenter==='function')return [...new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(value)].map(x=>x.segment);const result=[];for(const c of Array.from(value.normalize('NFC'))){if(result.length&&(/\p{Mark}/u.test(c)||/[\uFE0E\uFE0F\u200D]/u.test(c)||result.at(-1).endsWith('\u200D')||/[\u{1F3FB}-\u{1F3FF}]/u.test(c)))result[result.length-1]+=c;else result.push(c)}return result}
export function transcriptionProgress(base){return Math.max(0,Math.min(1,base/.7))}
export function responseGate(base){return Math.max(0,Math.min(1,(base-.7)/.3))}
export function transcribedText(value,progress){const parts=graphemes(value);return parts.slice(0,Math.floor(parts.length*Math.max(0,Math.min(1,progress)))).join('')}
export function activeTurnAt(tops,height){let active=-1;tops.forEach((top,i)=>{if(top<=height*.72)active=i});return active}
export function establishedFacts(data,active){return data.turns.slice(0,Math.max(0,active+1)).flatMap(t=>t.facts)}
export function renderGuidedDemo(data,{portrait='../guided-demo/assets/patient-29-transparent.png',showIntro=true}={}){
 const l=data.labels,ko=data.lang==='ko',domains=coveredDomains(data),root=el('section','guided-demo gd-scroll-demo');root.id='guided-demo';root.setAttribute('aria-label',l.subtitle);
 const reduced=typeof window!=='undefined'&&window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
 const heading=el('div','gd-head');heading.append(p(l.notice,'gd-notice'),p(ko?'음성 입력 예시 · 실제 녹음 없이, 스크롤로 전사 과정을 보여줍니다.':'Voice-input example · Scroll simulates transcription; no microphone is used.','gd-voice-notice'),el('h2','gd-title',l.title),p(l.subtitle,'gd-subtitle'),p(ko?'아래로 스크롤하며 학생의 질문, SP의 답변, 근거를 따라가세요.':'Scroll down through the student’s questions, SP responses and their evidence.','gd-scroll-hint'));
 function link(label,href,cls=''){const a=el('a',cls,label);a.href=href;return a}
 const nav=el('nav','gd-scroll-nav');nav.setAttribute('aria-label',ko?'시연 구간 이동':'Walkthrough sections');nav.append(link(ko?'처음 대화':'Opening','#gd-turn-1'),link(ko?'잘못된 질문과 SP 대처':'Mistaken premise','#gd-turn-8'),link(ko?'채점과 피드백':'Scoring & feedback','#gd-evaluation'));
 const shell=el('div','gd-scroll-shell'),aside=el('aside','gd-scroll-sidebar'),sticky=el('div','gd-scroll-sticky'),figure=el('figure','gd-person'),img=el('img');img.src=portrait;img.alt=l.portraitAlt;img.width=600;img.height=720;figure.append(img,el('figcaption',null,l.caseLabel));
 const summary=el('div','gd-live-facts'),summaryTitle=el('h3',null,ko?'지금까지의 대화':'Dialogue so far'),summaryFacts=el('div'),summaryStatus=p('','gd-scroll-status');summary.append(summaryTitle,summaryStatus,summaryFacts);sticky.append(figure,summary);aside.append(sticky);
 const timeline=el('div','gd-scroll-timeline'),revealNodes=[],responses=[],students=[];
 function reveal(n){revealNodes.push(n);return n}
 function bubble(role,value,cls,mark=''){const row=el('div','gd-speech '+cls),body=p(value,'gd-bubble');if(mark&&value.includes(mark)){const at=value.indexOf(mark);body.textContent='';body.append(el('span',null,value.slice(0,at)),el('span','gd-assumption',mark),el('span',null,value.slice(at+mark.length)))}row.append(p(role,'gd-role'),body);return row}
 data.turns.forEach((t,i)=>{const turn=el('article','gd-scroll-turn');turn.id='gd-turn-'+t.number;turn.append(el('h3','gd-turn-label',`${l.turn} ${String(t.number).padStart(2,'0')}`));
  const mark=t.number===8?(ko?'하루 다섯 잔씩 마셔서':'because you drink five cups of coffee a day'):t.number===11?(ko?'없으시죠':'do not stop breathing'):'';
  const student=reveal(bubble(l.student,t.student,'gd-student',mark)),patient=reveal(bubble(l.patient,t.patient,'gd-patient'));const body=student.children[1],source=el('span','gd-transcription-source'),overlay=el('span','gd-transcription-layer'),spoken=el('span','gd-transcription-text'),caret=el('span','gd-transcription-caret');source.append(...Array.from(body.childNodes||body.children||[]));if(!source.children.length)source.textContent=t.student;body.replaceChildren(source,overlay);overlay.setAttribute('aria-hidden','true');overlay.append(spoken,caret);body.className+=' gd-transcribing';const wave=el('span','gd-voice-wave');wave.setAttribute('aria-hidden','true');const bars=Array.from({length:5},()=>el('i'));wave.append(...bars);student.children[0].append(wave);student._transcription={source,overlay,spoken,caret,bars,parts:graphemes(t.student),value:t.student,mark,count:-1};students.push(student);patient._student=student;patient.id='gd-response-'+t.number;responses.push(patient);turn.append(student,patient);
  if(t.facts.length){const facts=reveal(el('div','gd-inline-facts'));facts._student=student;facts.append(p(l.facts,'gd-eyebrow'));t.facts.forEach(f=>{const row=el('div','gd-inline-fact');row.append(p(f.topic,'gd-fact-topic'),p(f.text),p(f.status==='patient_unknown'?l.unknown:f.status==='explicit_negative'?l.negative:l.known,'gd-fact-status'));facts.append(row)});if(t.number===8)facts.append(p(l.change,'gd-case-note'));if(t.number===11)facts.append(p(l.unknownNote,'gd-case-note'));turn.append(facts)}timeline.append(turn)
 });
 function source(n){return link(`${l.source} · ${String(n).padStart(2,'0')}`,'#gd-turn-'+n,'gd-source')}
 const evaluation=el('section','gd-scroll-evaluation');evaluation.id='gd-evaluation';evaluation.append(el('h3','gd-section-title',l.score));const score=reveal(el('div','gd-score-block'));score.append(p(l.scoreLabel,'gd-eyebrow'),p(`${domains.filter(d=>d.addressed).length} / ${domains.length}`,'gd-score'),p(l.scoreNote,'gd-fine'));const domainList=el('ul','gd-domains');domains.forEach(d=>{const li=el('li',d.addressed?'gd-addressed':'gd-missing');li.append(el('span',null,d.label),el('span',null,d.addressed?l.addressed:l.notAsked));domainList.append(li)});score.append(domainList,p(l.coverageNote,'gd-fine'),p(l.missedNote,'gd-fine'));evaluation.append(score,el('h3','gd-section-title',l.feedback));
 const good=reveal(el('div','gd-good'));good.append(el('h4',null,l.goodTitle),p('“'+l.goodQuote+'”'),p(l.goodText),source(9));evaluation.append(good);
 l.feedbackItems.forEach(item=>{const panel=reveal(el('div','gd-feedback-item'));panel.append(el('h4',null,item.title),p('“'+item.quote+'”','gd-original'),p(item.text,'gd-fine'),p(l.better,'gd-eyebrow'),p('“'+item.alternative+'”','gd-better'),source(item.turn));evaluation.append(panel)});
 const accuracy=reveal(el('div','gd-scroll-accuracy'));accuracy.append(el('h4',null,l.accuracy),p(l.accuracyText),source(11));evaluation.append(accuracy);
 const goals=reveal(el('div','gd-scroll-goals'));goals.append(el('h3','gd-section-title',l.goals),p(l.goalIntro));const goalsList=el('ol','gd-goals');l.goalItems.forEach(t=>goalsList.append(el('li',null,t)));goals.append(goalsList,link(ko?'처음부터 다시 읽기 ↑':'Read again from the beginning ↑','#gd-turn-1','gd-source'));evaluation.append(goals);timeline.append(evaluation);shell.append(aside,timeline);if(showIntro)root.append(heading);root.append(nav,shell);
 const readMode=el('button','gd-read-mode',ko?'모션 없이 모두 읽기':'Read all without motion');readMode.type='button';readMode.setAttribute('aria-pressed',String(!!reduced));nav.append(readMode);let staticMode=!!reduced,active=-2,frame=null,destroyed=false;
 function update(){frame=null;if(destroyed)return;const height=window.innerHeight||800;if(!responses[0]?.getBoundingClientRect){summaryStatus.textContent=ko?'스크롤로 직접 진행':'Advance by scrolling';return}for(const n of revealNodes){const progress=staticMode?1:scrollRevealProgress(n.getBoundingClientRect().top-(n._gdOffset||0),height);const studentBase=n._student?scrollRevealProgress(n._student.getBoundingClientRect().top-(n._student._gdOffset||0),height):1;const gate=staticMode?1:responseGate(studentBase);n.style.opacity=String(gate*(.22+.78*progress));n._gdOffset=staticMode?0:10*(1-progress);n.style.transform=`translateY(${n._gdOffset}px)`;n.style.setProperty?.('--scroll-progress',String(progress));if(n._transcription){const t=n._transcription,typing=staticMode?1:transcriptionProgress(progress),count=Math.floor(t.parts.length*typing),value=t.parts.slice(0,count).join('');t.overlay.style.display=staticMode?'none':'';t.source.style.color=staticMode?'inherit':'';t.source.className='gd-transcription-source'+(staticMode?' gd-show-source':'');if(count!==t.count){t.count=count;t.spoken.replaceChildren();if(t.mark&&value.includes(t.mark)){const at=value.indexOf(t.mark);t.spoken.append(el('span',null,value.slice(0,at)),el('span','gd-assumption',t.mark),el('span',null,value.slice(at+t.mark.length)))}else t.spoken.textContent=value;}t.caret.style.opacity=typing>0&&typing<1?'1':'0';t.bars.forEach((bar,i)=>{bar.style.height=(staticMode||typing<=0||typing>=1?3:4+Math.abs(Math.sin(count*.7+i*1.3))*9)+'px'});n.setAttribute('data-transcribed',String(count));}}const next=activeTurnAt(responses.map(n=>n.getBoundingClientRect().top-(n._gdOffset||0)),height);if(next!==active){active=next;summaryStatus.textContent=active<0?(ko?'면담 시작 전':'Before the interview'):`${l.turn} ${String(active+1).padStart(2,'0')} / 12`;summaryFacts.replaceChildren();const facts=establishedFacts(data,active);if(!facts.length)summaryFacts.append(p(l.noFacts,'gd-fine'));else facts.slice(-3).forEach(f=>summaryFacts.append(p(f.text,'gd-fine')));root.setAttribute('data-active-turn',String(active+1))}}
 function onScroll(){if(frame!==null||destroyed)return;if(typeof requestAnimationFrame==='function')frame=requestAnimationFrame(update);else update()}
 readMode.addEventListener('click',()=>{staticMode=!staticMode;readMode.setAttribute('aria-pressed',String(staticMode));readMode.textContent=staticMode?(ko?'스크롤 모션 켜기':'Enable scroll motion'):(ko?'모션 없이 모두 읽기':'Read all without motion');update()});
 window.addEventListener?.('scroll',onScroll,{passive:true});window.addEventListener?.('resize',onScroll);document.fonts?.ready?.then(onScroll);img.addEventListener?.('load',onScroll);onScroll();
 root.guidedDemoState=()=>({activeTurn:active,staticMode,mode:'native-scroll'});root.updateGuidedDemo=update;root.destroyGuidedDemo=()=>{destroyed=true;if(frame!==null&&typeof cancelAnimationFrame==='function')cancelAnimationFrame(frame);window.removeEventListener?.('scroll',onScroll);window.removeEventListener?.('resize',onScroll)};
 return root;
}
