const node=(tag,cls,value)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(value!==undefined)n.textContent=value;return n};
const p=(value,cls='')=>node('p',cls,value);
function link(label,href,cls=''){const a=node('a',cls,label);a.href=href;return a}
function action(label,fn,cls=''){const b=node('button',cls,label);b.type='button';b.addEventListener('click',fn);return b}
export function renderIntroduction(copy,{navigate,portrait='../guided-demo/assets/patient-29-transparent.png',notebook='../project-front/assets/case-notebook-transparent.png'}={}){
 const ko=copy.lang==='ko',intro=node('div','project-front');intro.setAttribute('lang',copy.lang);intro.id='overview';
 const hero=node('section','front-hero'),title=node('h1','project-title',copy.headline);hero.append(p(copy.eyebrow,'front-eyebrow'),title);
 const body=node('div','front-hero-body'),words=node('div','front-hero-words');words.append(p(copy.lead,'front-lead'),p(copy.byline,'front-byline'),p(copy.languageNote,'front-language-note'));
 const actions=node('div','front-actions');actions.append(link(copy.primary+' ↓','#project-demo','front-primary'),action(copy.secondary,()=>navigate('practice'),'front-secondary'));words.append(actions);
 const figure=node('figure','front-portrait'),img=node('img');img.src=portrait;img.alt=ko?'연습 면담에서 이야기를 들려주는 젊은 가상 환자의 삽화':'An illustrated fictional young adult patient in a practice interview';img.width=600;img.height=720;figure.append(img);body.append(words,figure);hero.append(body);
 const rail=node('ol','front-loop-rail');(ko?['증례','면담','근거 복습','재연습']:['Case','Conversation','Review','Another attempt']).forEach((label,i)=>{const li=node('li');li.append(node('span','front-number',String(i+1).padStart(2,'0')),node('span',null,label));rail.append(li)});hero.append(rail);intro.append(hero);
 const story=node('section','front-story');story.append(node('h2',null,copy.storyTitle));const paragraphs=node('div');copy.paragraphs.forEach(value=>paragraphs.append(p(value)));story.append(paragraphs);intro.append(story);
 const loop=node('section','front-loop');loop.append(node('h2',null,copy.loopTitle));const list=node('ol','front-loop-list');copy.loop.forEach((value,i)=>{const li=node('li');const image=node('img','front-loop-image');image.src=i===0||i===2?notebook:portrait;image.alt='';image.width=120;image.height=120;li.append(image,node('span','front-number',String(i+1).padStart(2,'0')),p(value));list.append(li)});loop.append(list);intro.append(loop);return intro;
}
export function renderDemoIntroduction(copy){const section=node('section','front-demo-intro');section.id='project-demo';section.tabIndex=-1;section.append(p(copy.demoStatus,'front-eyebrow'),node('h2',null,copy.demoTitle),p(copy.demoIntro));return section}
export function renderFoundation(copy,{navigate,brief="../PROJECT-BRIEF.md",portrait="../guided-demo/assets/patient-29-transparent.png"}={}){const ko=copy.lang==='ko',section=node('section','front-foundation'),review=copy.portfolio;section.append(node('h2',null,copy.afterTitle),p(copy.working,'front-working'),p(ko?'가상 증례 3개 · 사실 54개 · 질문 의도 36개 · 등록 표현 108개':'3 fictional cases · 54 facts · 36 question intents · 108 registered expressions','front-facts-strip'));
 const api=node('section','front-api');api.id='why-claude';api.append(node('h2',null,review.title),p(review.lead,'front-api-lead'));review.roles.forEach((role,i)=>{const row=node('div','front-api-role');row.append(node('span','front-number',String(i+1).padStart(2,'0')));const body=node('div');body.append(node('h3',null,role.title),p(role.text));if(i===0){const sample=node('div','front-patient-example'),question=node('div'),patient=node('div'),image=node('img');question.append(p(ko?'학생의 질문':'Student question','front-sample-label'),p(copy.apiExample.question,'front-sample-question'));image.src=portrait;image.alt='';image.width=100;image.height=120;patient.append(p(ko?'증례에 근거한 SP 응답':'Case-grounded SP response','front-sample-label'),p(copy.apiExample.patient,'front-sample-answer'));sample.append(question,image,patient);body.append(sample,p(copy.apiExample.constraint,'front-constraint'),p(review.example,'front-api-example'))}if(i===1){const sample=node('div','front-feedback-example'),original=node('div'),revision=node('div');original.append(p(ko?'실제 학생 발화':'Actual student quote','front-sample-label'),p(copy.apiExample.question,'front-sample-question'),p(copy.apiExample.observation,'front-sample-observation'));revision.append(p(ko?'피드백으로 바꾼 질문':'A revised question','front-sample-label'),p(copy.apiExample.alternative,'front-sample-answer'));sample.append(original,p('→','front-sample-arrow'),revision);body.append(sample,link(ko?'근거 대화로 돌아가기':'Return to the source exchange','#gd-turn-8','front-source-link'))}row.append(body);api.append(row)});section.append(api);
 const support=node('section','front-support');support.append(node('h3',null,review.supportTitle),p(review.support));section.append(support,p(review.stage,'front-stage'),p(copy.creator,'front-creator'),action(copy.secondary,()=>navigate('practice'),'front-secondary'));const links=node('div','front-footer-links');links.append(link(ko?'GitHub 소스':'GitHub source','https://github.com/choiseungri/cpx-english-review'),link(ko?'프로젝트 소개서':'Project brief',brief));section.append(links,p(copy.footerNote,'front-safety'));return section}

export function languageTarget(lang,hash=''){const safe=['project','practice','review','editor','about'].includes(hash.replace(/^#/,''))?hash:'#project';return (lang==='ko'?'../site/index.html':'../en/index.html')+safe}
export function initLanguageSwitch(){function update(){document.querySelectorAll('[data-language]').forEach(a=>{a.href=languageTarget(a.getAttribute?.('data-language')||a.dataset?.language,window.location?.hash||'')})}update();window.addEventListener?.('hashchange',update);window.addEventListener?.('popstate',update);return update}

export function isProjectAnchor(hash=''){return /^#(?:overview|project-demo|why-claude|guided-demo|gd-turn-\d+|gd-evaluation)$/.test(hash)}
